{{- range .Values.mounts }}
{{- if eq .type "vault" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kubernetes.name" $ }}
  labels:
    {{- include "kubernetes.labels" $ | nindent 4 }}
  annotations:
    helmDate: {{ now | date "2006-01-02T15:04:05" }}
spec:
  refreshInterval: {{ default "5m" .refreshInterval }}
  secretStoreRef:
    name: {{ default "vault" .secretStore }}
    kind: SecretStore
  target:
    name: {{ .name }}
  dataFrom:
  - extract:
      key: {{ .vaultPath }}
{{- end }}
{{- end }}
