name: Deployment to Minikube

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: arc-runner-set
    container:
      image: alpine/k8s:1.28.7
    permissions:
      contents: read
    steps:
    - name: Deploy
      run: |
        git clone https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
        cd ${{ github.event.repository.name }}
        helm install \
          ${{ github.event.repository.name }} kubernetes \
          --set image.repository=${{ env.REGISTRY }} \
          --set image.tag=${{ env.IMAGE_NAME }} \
          --set imagePullSecrets[0]=ghcr \
          --set ports.name=http \
          --set ports.containerPort=8080
