name: Deployment to Minikube

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: arc-runner-set
    container:
      image: alpine/k8s:1.28.7
    steps:
    - name: Deploy
      run: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        cd ${GITHUB_REPOSITORY}
        helm install \
          ${{ github.event.repository.name }} kubernetes \
          --set image.repository=${{ env.REGISTRY }} \
          --set image.tag=${{ env.IMAGE_NAME }} \
          --set imagePullSecrets=ghcr, \
          --set ports.name=http \
          --set ports.containerPort=8080
