name: Deployment to Kubernetes

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
  HELM_RELEASE_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
  KUBERNETES_NAMESPACE: ${{ github.event.repository.name }}-${{ github.ref_name }}

jobs:
  container-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  deployment-to-kubernetes:
    runs-on: arc-runner-set
    needs: container-image-build
    container:
      image: alpine/k8s:1.28.7
    permissions:
      contents: read
    steps:
    - name: Deployment to Kubernetes
      run: |
        git clone -b ${{ github.ref_name }} https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
        cd ${{ github.event.repository.name }}
        kubectl create namespace $KUBERNETES_NAMESPACE >/dev/null || true
        helm upgrade --install $HELM_RELEASE_NAME kubernetes \
          --namespace $KUBERNETES_NAMESPACE \
          --set image.repository=$IMAGE_NAME \
          --set image.tag=$IMAGE_TAG \
          --set imagePullSecrets[0]=ghcr \
          --set ports[0].containerPort=8080 \
          --set service.containerPort=8080
